 document.getElementById('home').addEventListener('tap',function(){
      mui.openWindow({
          url:'demo.html',
          id:'demo.html',
          styles:{
            top:'45px',//新页面顶部位置
            bottom:'45px',//新页面底部位置
          },
          extras:{
          },
          createNew:false,//是否重复创建同样id的webview，默认为false:不重复创建，直接显示
          show:{
            autoShow:true,//页面loaded事件发生后自动显示，默认为true
          },
          waiting:{
            autoShow:true,//自动显示等待框，默认为true
            title:'正在加载...',//等待对话框上显示的提示内容
            options:{
            }
          }
      })

    })
    document.getElementById('sousuo').addEventListener('tap',function(){
      mui.openWindow({
          url:'geren.html',
          id:'geren.html',
          styles:{
            top:'45px',//新页面顶部位置
            bottom:'45px',//新页面底部位置
          },
          extras:{
          },
          createNew:false,//是否重复创建同样id的webview，默认为false:不重复创建，直接显示
          show:{
            autoShow:true,//页面loaded事件发生后自动显示，默认为true
          },
          waiting:{
            autoShow:true,//自动显示等待框，默认为true
            title:'正在加载...',//等待对话框上显示的提示内容
            options:{
            }
          }
      })

    })
    document.getElementById('person').addEventListener('tap',function(){
      mui.openWindow({
          url:'geren.html',
          id:'geren.html',
          styles:{
            top:'45px',//新页面顶部位置
            bottom:'45px',//新页面底部位置
          },
          extras:{
          },
          createNew:false,//是否重复创建同样id的webview，默认为false:不重复创建，直接显示
          show:{
            autoShow:true,//页面loaded事件发生后自动显示，默认为true
          },
          waiting:{
            autoShow:true,//自动显示等待框，默认为true
            title:'正在加载...',//等待对话框上显示的提示内容
            options:{
            }
          }
      })

    })